// All menu items
const menuItems = [
  // STARTER (ANTIPASTI)
  {
    id: 'gol-gappe-10',
    name: 'GOL GAPPE (10 PZ)',
    description: 'Farina di riso tipo 0, ceci, patate, tamarindo, menta',
    price: 6.90,
    categoryId: 'starter',
    image: '/new menu/Starter(Antipasti)-(6)/01. GOL GAPPE(10Pz).jpg',
  },
  {
    id: 'sabzi-samosa-1',
    name: 'SABZI SAMOSA 1 PZ',
    description: 'Patate, farina 00, spezie',
    price: 2.00,
    categoryId: 'starter',
    image: '/new menu/Starter(Antipasti)-(6)/02. SABJI SAMOSA 1Pz.jpg',
  },
  {
    id: 'tikki-chat',
    name: 'TIKKI CHAT',
    description: 'Polpette di verdure, ceci, salsa alla menta, salsa dolco, pomodori, cetrioli',
    price: 4.90,
    categoryId: 'starter',
    image: '/new menu/Starter(Antipasti)-(6)/03. TIKKI CHAT.jpg',
  },
  {
    id: 'samosa-chat',
    name: 'SAMOSA CHAT',
    description: 'Farina tipo 00, verdure miste, ceci, salsa menta, salsa dolce',
    price: 4.90,
    categoryId: 'starter',
    image: '/new menu/Starter(Antipasti)-(6)/04. SAMOSA CHAT.jpg',
  },
  {
    id: 'mix-pakora',
    name: 'MIX PAKORA',
    description: 'Farina di ceci, spezie, patate, cipolla',
    price: 4.90,
    categoryId: 'starter',
    image: '/new menu/Starter(Antipasti)-(6)/05. MIX PAKORA.jpg',
  },
  {
    id: 'vegetable-spring-roll-2',
    name: 'VEGETABLE SPRING ROLL 2 PZ',
    description: 'Farina tipo 00, verdure miste, spezie',
    price: 3.90,
    categoryId: 'starter',
    image: '/new menu/Starter(Antipasti)-(6)/06. VEGETABLE SPRING ROLL 2 Pz.jpg',
  },

  // FRIED (FRITTI)
  {
    id: 'fish-pakora-5',
    name: 'FISH PAKORA 5 PZ',
    description: 'Pangasio, farina di ceci, spezie',
    price: 6.90,
    categoryId: 'fried',
    image: '/new menu/Fried(Fritti)- (4)/07. FISH PAKODAB 5Pz.jpg',
  },
  {
    id: 'chapli-kabab-2',
    name: 'CHAPLI KABAB 2 PZ',
    description: 'Carne di manzo, spezie',
    price: 4.90,
    categoryId: 'fried',
    image: '/new menu/Fried(Fritti)- (4)/08. CHAPLI KABAB 2Pz.jpg',
  },
  {
    id: 'chicken-nuggets-patatine',
    name: 'CHICKEN NUGGETTS + PATATINE',
    description: '',
    price: 7.90,
    categoryId: 'fried',
    image: '/new menu/Fried(Fritti)- (4)/09. CHICKEN NUGGETTS + PATATINE.jpg',
  },
  {
    id: 'patatine-fritte',
    name: 'PATATINE FRITTE',
    description: '',
    price: 3.90,
    categoryId: 'fried',
    image: '/new menu/Fried(Fritti)- (4)/10. PATATINE FRITTE.jpg',
  },

  // GRILL
  {
    id: 'chicken-wing-5',
    name: 'CHICKEN WING 5 PZ',
    description: 'Alette di pollo, spezie',
    price: 7.90,
    categoryId: 'grill',
    image: '/new menu/Grill-(6)/11. CHICKEN WING 5Pz.jpg',
  },
  {
    id: 'chicken-leg-1',
    name: 'CHICKEN LEG 1 PZ',
    description: 'Cosco di pollo, spezie',
    price: 6.90,
    categoryId: 'grill',
    image: '/new menu/Grill-(6)/12. CHICKEN LEG 1Pz.jpg',
  },
  {
    id: 'chicken-tikka',
    name: 'CHICKEN TIKKA',
    description: 'Dadini di pollo, spezie',
    price: 9.90,
    categoryId: 'grill',
    image: '/new menu/Grill-(6)/13.CHICKEN TIKKA.jpg',
    isTopSeller: true,
  },
  {
    id: 'chicken-seekh-kabab',
    name: 'CHICKEN SEEKH KABAB',
    description: 'Macinato di pollo, spezie',
    price: 9.90,
    categoryId: 'grill',
    image: '/new menu/Grill-(6)/14. CHICKEN SEEK KABAB.jpg',
  },
  {
    id: 'cheekh-kabab',
    name: 'CHEEKH KABAB',
    description: 'Macinato di manzo, formaggio, spezie',
    price: 9.90,
    categoryId: 'grill',
    image: '/new menu/Grill-(6)/15. CHICKEN KABAB.jpg',
  },
  {
    id: 'mix-grill',
    name: 'MIX GRILL',
    description: 'Chicken tika, seekh kebab, chanp, chicken wings',
    price: 29.90,
    categoryId: 'grill',
    image: '/new menu/Grill-(6)/16. MIX GRILL.jpg',
    isTopSeller: true,
  },

  // CHICKEN (POLLO)
  {
    id: 'white-chicken',
    name: 'WHITE CHICKEN',
    description: 'Pollo, yogurt, crema e spezie indiane',
    price: 6.90,
    categoryId: 'chicken',
    image: '/new menu/Chicken (Pollo)/17. WHITE CHICKEN.jpg',
  },
  {
    id: 'chicken-karahi',
    name: 'CHICKEN KARAHI',
    description: 'Pollo, peperoncino verde, spezie',
    price: 6.90,
    categoryId: 'chicken',
    image: '/new menu/Chicken (Pollo)/18. CHICKEN KARAHI.jpg',
    isTopSeller: true,
  },
  {
    id: 'kabab-massala',
    name: 'KABAB MASSALA',
    description: 'Seekh kabab, spezie',
    price: 6.90,
    categoryId: 'chicken',
    image: '/new menu/Chicken (Pollo)/19. KABAB MASSALA.jpg',
  },
  {
    id: 'chicken-tikka-massala',
    name: 'CHICKEN TIKKA MASSALA',
    description: 'Dadini di pollo cotti in forna tandoori, spezie',
    price: 7.90,
    categoryId: 'chicken',
    image: '/new menu/Chicken (Pollo)/20. CHICKEN TIKKA MASsALA.jpg',
  },
  {
    id: 'butter-chicken',
    name: 'BUTTER CHICKEN',
    description: 'Pollo cotto in forno tandoori, mandorle, panna, spezie',
    price: 6.90,
    categoryId: 'chicken',
    image: '/new menu/Chicken (Pollo)/21. BUTTER CHICKEN.jpg',
    isTopSeller: true,
  },
  {
    id: 'chicken-korma',
    name: 'CHICKEN KORMA',
    description: 'Pollo cocco, saisa curry, spezie',
    price: 6.90,
    categoryId: 'chicken',
    image: '/new menu/Chicken (Pollo)/22. CHICKEN KORMA.jpg',
  },
  {
    id: 'haleem',
    name: 'HALEEM',
    description: 'Carne di pollo, lenticche, zenzero, spezie',
    price: 4.90,
    categoryId: 'chicken',
    image: '/new menu/Chicken (Pollo)/23. HALEEM.jpg',
  },
  {
    id: 'lahori-chana',
    name: 'LAHORI CHANA',
    description: 'Fagioli e spezie indiane',
    price: 4.90,
    categoryId: 'chicken',
    image: '/new menu/Chicken (Pollo)/24. LAHORE CHANA.jpg',
  },

  // SPECIAL KARAHI (CHICKEN)
  {
    id: 'shaneari-1kg',
    name: 'SHANEARI (1KG)',
    description: 'Fagioli e spezie indiane',
    price: 29.90,
    categoryId: 'special_chicken_karahi',
    image: '/new menu/Special Karahi- (2)/25. SHANEARI (1KG).jpg',
  },
  {
    id: 'chicken-karahi-1kg',
    name: 'CHICKEN KARAHI (1KG)',
    description: 'Pollo, spezie',
    price: 29.90,
    categoryId: 'special_chicken_karahi',
    image: '/new menu/Special Karahi- (2)/26. CHICKEN KARAHI (1KG).jpg',
    isTopSeller: true,
  },

  // LAMB KARAHI (AGNELLO)
  {
    id: 'karahi-gosht',
    name: 'KARAHI GOSHT',
    description: 'Carne di agnello, pomodoro, zenzero, spezie',
    price: 9.90,
    categoryId: 'lamb_karahi',
    image: '/new menu/Lamb Karahi(Angello) - (6)/27. KARAHI GOSHT.jpg',
  },
  {
    id: 'qeema',
    name: 'QEEMA',
    description: 'Carne macinata di agnello, spezie',
    price: 8.90,
    categoryId: 'lamb_karahi',
    image: '/new menu/Lamb Karahi(Angello) - (6)/28. QEEMA.jpg',
  },
  {
    id: 'bhindi-gosht',
    name: 'BHINDI GOSHT',
    description: 'Carne di agnello, salsa verdure, spezie',
    price: 7.90,
    categoryId: 'lamb_karahi',
    image: '/new menu/Lamb Karahi(Angello) - (6)/29. BHINDI GOSHT.jpg',
  },
  {
    id: 'lamb-curry',
    name: 'LAMB CURRY',
    description: 'Carne di agnello, pomodoro, zenzero, spezie',
    price: 9.90,
    categoryId: 'lamb_karahi',
    image: '/new menu/Lamb Karahi(Angello) - (6)/30. LAMB CURRY.jpg',
  },
  {
    id: 'beef',
    name: 'BEEF',
    description: 'Agnello con osso, spezie',
    price: 9.90,
    categoryId: 'lamb_karahi',
    image: '/new menu/Lamb Karahi(Angello) - (6)/31. BEEF.jpg',
  },
  {
    id: 'paye',
    name: 'PAYE',
    description: 'Piedi di mucca, spezie',
    price: 7.90,
    categoryId: 'lamb_karahi',
    image: '/new menu/Lamb Karahi(Angello) - (6)/32. PAYE.jpg',
  },

  // SPECIAL KARAHI (LAMB)
  {
    id: 'karahi-gosht-1kg',
    name: 'KARAHI GOSHT (1KG)',
    description: 'Carne di agnello, pepe nero, sale, spezie',
    price: 34.00,
    categoryId: 'special_lamb_karahi',
    image: '/new menu/Special_Karahi - (3)/33. KARAHI GOHST (1 KG)- 34.jpg',
  },
  {
    id: 'karahi-gosht-half-kg',
    name: 'KARAHI GOSHT (1/2KG)',
    description: 'Carne di agnello, pepe nero, sale, spezie',
    price: 17.00,
    categoryId: 'special_lamb_karahi',
    image: '/new menu/Special_Karahi - (3)/33. KARAHI GOHST (1 KG)- 34.jpg',
  },
  {
    id: 'namkeen-karahi-1kg',
    name: 'NAMKEEN KARAHI (1KG)',
    description: 'Carne di agnello, pomodoro, zenzero, spezie',
    price: 34.00,
    categoryId: 'special_lamb_karahi',
    image: '/new menu/Special_Karahi - (3)/34. NAMKEEN KARAHI (1KG)-34.jpg',
  },
  {
    id: 'namkeen-karahi-half-kg',
    name: 'NAMKEEN KARAHI (1/2KG)',
    description: 'Carne di agnello, pomodoro, zenzero, spezie',
    price: 17.00,
    categoryId: 'special_lamb_karahi',
    image: '/new menu/Special_Karahi - (3)/34. NAMKEEN KARAHI (1KG)-34.jpg',
  },
  {
    id: 'white-karahi-1kg',
    name: 'WHITE KARAHI (1KG)',
    description: 'Carne di agnello, pomodoro, zenzero, yogurt, spezie',
    price: 32.00,
    categoryId: 'special_lamb_karahi',
    image: '/new menu/Special_Karahi - (3)/35. WHITE KARAHI (1KG)- 32.jpg',
  },
  {
    id: 'white-karahi-half-kg',
    name: 'WHITE KARAHI (1/2KG)',
    description: 'Carne di agnello, pomodoro, zenzero, yogurt, spezie',
    price: 16.00,
    categoryId: 'special_lamb_karahi',
    image: '/new menu/Special_Karahi - (3)/35. WHITE KARAHI (1KG)- 32.jpg',
  },

  // VEGETABLE (VEGETARIANI)
  {
    id: 'palak-paneer',
    name: 'PALAK PANEER',
    description: 'Spinaci, formaggio, panna, curry, spezie',
    price: 6.90,
    categoryId: 'vegetable',
    image: '/new menu/Vagitable (Vegetariani)/36. PALAK PANEER.jpg',
  },
  {
    id: 'kari-pakora',
    name: 'KARI PAKORA',
    description: 'Yogurt, verdure, spezie',
    price: 6.90,
    categoryId: 'vegetable',
    image: '/new menu/Vagitable (Vegetariani)/37. KAHI PAKORA.jpg',
  },
  {
    id: 'bhindi-masala',
    name: 'BHINDI MASALA',
    description: 'Verdure indiane, pomodori, curry, spezie',
    price: 6.90,
    categoryId: 'vegetable',
    image: '/new menu/Vagitable (Vegetariani)/38. BHINDI MASALA.jpg',
  },
  {
    id: 'mix-sabzi',
    name: 'MIX SABZI',
    description: 'Misto di verdure, curry, spezie',
    price: 6.90,
    categoryId: 'vegetable',
    image: '/new menu/Vagitable (Vegetariani)/39. MIX SABJI.jpg',
  },
  {
    id: 'daal-tarka',
    name: 'DAAL TARKA',
    description: 'Lenticchie di ceci, curry, spezie',
    price: 5.90,
    categoryId: 'vegetable',
    image: '/new menu/Vagitable (Vegetariani)/40. DAAL TARKA.jpg',
  },
  {
    id: 'chole-bhature-2',
    name: 'CHOLE BHATURE 2 PZ',
    description: 'Ceci, spezie',
    price: 5.90,
    categoryId: 'vegetable',
    image: '/new menu/Vagitable (Vegetariani)/41. CHOLA BHATURE 2pz.jpg',
  },
  {
    id: 'manchurian',
    name: 'MANCHURIAN',
    description: 'Cipolle, peperoni, spezie, polpette di verdure',
    price: 6.90,
    categoryId: 'vegetable',
    image: '/new menu/Vagitable (Vegetariani)/42. MANCHURIAN.jpg',
  },

  // INSALATA
  {
    id: 'insalata-piatto-grande',
    name: 'PIATTO GRANDE',
    description: '',
    price: 7.90,
    categoryId: 'insalata',
    image: '/new menu/Insalata - (3)/43. PIATTO GRANDE.jpg',
  },
  {
    id: 'insalata-piatto-piccolo',
    name: 'PIATTO PICCOLO',
    description: '',
    price: 6.00,
    categoryId: 'insalata',
    image: '/new menu/Insalata - (3)/44. PIATTO PICOOLO.jpg',
  },
  {
    id: 'insalatone',
    name: 'INSALATONE',
    description: '',
    price: 6.00,
    categoryId: 'insalata',
    image: '/new menu/Insalata - (3)/45. INSALATONE.jpg',
  },

  // PANE TANDOOR
  {
    id: 'roti',
    name: 'ROTI',
    description: 'Farina integrale, acqua, sale',
    price: 2.00,
    categoryId: 'pane',
    image: '/new menu/Pane Tandoor/46. ROTI.jpg',
  },
  {
    id: 'sada-naan',
    name: 'SADA NAAN',
    description: 'Farina 00, acqua, sale, lievito',
    price: 2.00,
    categoryId: 'pane',
    image: '/new menu/Pane Tandoor/47. SADA NAAN.jpg',
  },
  {
    id: 'afghani-naan',
    name: 'AFGHANI NAAN',
    description: 'Farina 00, acqua, sale, formaggio, lievito',
    price: 3.00,
    categoryId: 'pane',
    image: '/new menu/Pane Tandoor/48. AFGHANI NAAN.jpg',
  },
  {
    id: 'roghni-naan',
    name: 'ROGHNI NAAN',
    description: 'Farina 00, acqua, sale, formaggio, lievito',
    price: 2.00,
    categoryId: 'pane',
    image: '/new menu/Pane Tandoor/49. ROGHNI NAAN.jpg',
  },
  {
    id: 'butter-naan',
    name: 'BUTTER NAAN',
    description: 'Farina 00, burro, lievito',
    price: 2.00,
    categoryId: 'pane',
    image: '/new menu/Pane Tandoor/50. BUTTER NAAN.jpg',
  },
  {
    id: 'cheese-naan',
    name: 'CHEESE NAAN',
    description: 'Farina 00, acqua, sale, formaggio, lievito',
    price: 3.00,
    categoryId: 'pane',
    image: '/new menu/Pane Tandoor/51. CHEESE NAAN.jpg',
  },
  {
    id: 'garlic-naan',
    name: 'GARLIC NAAN',
    description: 'Farina 00, aglio',
    price: 3.00,
    categoryId: 'pane',
    image: '/new menu/Pane Tandoor/52. GARLIC NAAN.jpg',
  },
  {
    id: 'alu-naan',
    name: 'ALU NAAN',
    description: 'Farina 00, acqua, sale, burro, patate, lievito',
    price: 3.50,
    categoryId: 'pane',
    image: '/new menu/Pane Tandoor/53. ALU NAAN.jpg',
  },
  {
    id: 'qeema-naan',
    name: 'QEEMA NAAN',
    description: 'Farina 00, acqua, latte, macinato di manzo, lievito',
    price: 4.00,
    categoryId: 'pane',
    image: '/new menu/Pane Tandoor/54. QEEMA NAAN.jpg',
  },
  {
    id: 'kulcha',
    name: 'KULCHA',
    description: 'Farina 00, acqua, sale, semi di sesamo, lievito',
    price: 3.00,
    categoryId: 'pane',
    image: '/new menu/Pane Tandoor/55. KULCHA.jpg',
  },
  {
    id: 'butter-roti',
    name: 'BUTTER ROTI',
    description: 'Farina integrale, acqua, burro, sale',
    price: 2.00,
    categoryId: 'pane',
    image: '/new menu/Pane Tandoor/56. BUTTER ROTI.jpg',
  },
  {
    id: 'khamir-roti',
    name: 'KHAMIR ROTI',
    description: 'Farina 00, acqua, lievito, sale',
    price: 2.00,
    categoryId: 'pane',
    image: '/new menu/Pane Tandoor/57. KHAMIR ROTI.jpg',
  },

  // RISO
  {
    id: 'riso-bianco',
    name: 'RISO BIANCO',
    description: 'Riso basmati',
    price: 4.90,
    categoryId: 'riso',
    image: '/new menu/Riso/58. RISO BIANCO.jpg',
  },
  {
    id: 'chicken-biryani',
    name: 'CHICKEN BIRYANI',
    description: 'Riso basmati, pollo, curry, spezie',
    price: 7.90,
    categoryId: 'riso',
    image: '/new menu/Riso/59. CHICKEN BIRYANI.jpg',
    isTopSeller: true,
  },
  {
    id: 'lamb-biryani',
    name: 'LAMB BIRYANI',
    description: 'Riso basmati, agnello, curry, spezie',
    price: 8.90,
    categoryId: 'riso',
    image: '/new menu/Riso/62. LAMB BIRYANI.jpg',
  },
  {
    id: 'sabzi-biryani',
    name: 'SABZI BIRYANI',
    description: 'Riso basmati, verdure miste, curry, spezie',
    price: 7.90,
    categoryId: 'riso',
    image: '/new menu/Riso/60. SABJI BIRYANI.jpg',
  },
  {
    id: 'afghani-palao',
    name: 'AFGHANI PALAO',
    description: '',
    price: 8.90,
    categoryId: 'riso',
    image: '/new menu/Riso/61. AFGHANI PULAO.jpg',
  },

  // CAFETERIA
  {
    id: 'peshawari-gawa',
    name: 'PESHAWARI GAWA',
    description: '',
    price: 1.50,
    categoryId: 'cafeteria',
    image: '/new menu/Drink 7_menu/Cafeteria/62. PESHAWARI GAWA.jpg',
  },
  {
    id: 'chai',
    name: 'CHAI',
    description: 'Latte fresco, the lipton',
    price: 2.50,
    categoryId: 'cafeteria',
    image: '/new menu/Drink 7_menu/Cafeteria/63. CHAI.jpg',
  },
  {
    id: 'kashmiri-chai',
    name: 'KASHMIRI CHAI',
    description: 'Latte fresco, frutta secca, the verde',
    price: 2.50,
    categoryId: 'cafeteria',
    image: '/new menu/Drink 7_menu/Cafeteria/64. KASHMIRI CHAI.jpg',
  },
  {
    id: 'caffe',
    name: 'CAFFÈ',
    description: '',
    price: 1.00,
    categoryId: 'cafeteria',
    image: '/new menu/Drink 7_menu/Cafeteria/65. CAFFE.jpg',
  },
  {
    id: 'cappuccino',
    name: 'CAPPUCCINO',
    description: '',
    price: 1.50,
    categoryId: 'cafeteria',
    image: '/new menu/Drink 7_menu/Cafeteria/66. CAPPUCCINO.jpg',
  },

  // SOFT DRINKS
  {
    id: 'acqua-naturale',
    name: 'ACQUA NATURALE (0.75ML)',
    description: '',
    price: 1.90,
    categoryId: 'soft_drinks',
    image: '/new menu/Drink 7_menu/Soft Drink/Acqua naturale .jpg',
  },
  {
    id: 'acqua-frizzante',
    name: 'ACQUA FRIZANTE (0.75ML)',
    description: '',
    price: 1.90,
    categoryId: 'soft_drinks',
    image: '/new menu/Drink 7_menu/Soft Drink/Acqua Frizante.jpg',
  },
  {
    id: 'coca-cola',
    name: 'COCA COLA',
    description: '',
    price: 3.00,
    categoryId: 'soft_drinks',
    image: '/new menu/Drink 7_menu/Soft Drink/Coca-Cola lattina 33 cl.jpg',
  },
  {
    id: 'coca-cola-zero',
    name: 'COCA COLA ZERO',
    description: '',
    price: 3.00,
    categoryId: 'soft_drinks',
    image: '/new menu/Drink 7_menu/Soft Drink/coca cola zero.jpg',
  },
  {
    id: 'sprite',
    name: 'SPRITE',
    description: '',
    price: 3.00,
    categoryId: 'soft_drinks',
    image: '/new menu/Drink 7_menu/Soft Drink/Sprite lattina 33 cl.jpg',
  },
  {
    id: 'fanta',
    name: 'FANTA',
    description: '',
    price: 3.00,
    categoryId: 'soft_drinks',
    image: '/new menu/Drink 7_menu/Soft Drink/Fanta lattina 33 cl.jpg',
  },
  {
    id: 'lemon-soda',
    name: 'LEMON SODA',
    description: '',
    price: 3.00,
    categoryId: 'soft_drinks',
    image: '/new menu/Drink 7_menu/Soft Drink/lemon soda.jpg',
  },
  {
    id: 'the-pesca',
    name: 'THE AL PESCA',
    description: '',
    price: 3.00,
    categoryId: 'soft_drinks',
    image: '/new menu/Drink 7_menu/Soft Drink/Te Pesca.jpg',
  },
  {
    id: 'the-lemon',
    name: 'THE AL LEMON',
    description: '',
    price: 3.00,
    categoryId: 'soft_drinks',
    image: '/new menu/Drink 7_menu/Soft Drink/Te Limone.jpg',
  },
  {
    id: 'redbull',
    name: 'REDBULL',
    description: '',
    price: 3.00,
    categoryId: 'soft_drinks',
    image: '/new menu/Drink 7_menu/Soft Drink/Red Bull.jpg',
  },
  {
    id: 'monster',
    name: 'MONSTER',
    description: '',
    price: 3.00,
    categoryId: 'soft_drinks',
    image: '/new menu/Drink 7_menu/Soft Drink/Monster.jpg',
  },

  // LASSI
  {
    id: 'mango-lassi',
    name: 'MANGO LASSI',
    description: 'Frullato di mango, yogurt, zucchero',
    price: 3.50,
    categoryId: 'lassi',
    image: '/new menu/Drink 7_menu/Lassi/78. MANGO LASSI.jpg',
  },
  {
    id: 'lassi-mithi',
    name: 'LASSI MITHI',
    description: 'Frullato di yogurt, zucchero',
    price: 3.00,
    categoryId: 'lassi',
    image: '/new menu/Drink 7_menu/Lassi/79. LASSI MITHI.jpg',
  },
  {
    id: 'namkeen-lassi',
    name: 'NAMKEEN LASSI',
    description: 'Frullato di yogurt, sale',
    price: 3.00,
    categoryId: 'lassi',
    image: '/new menu/Drink 7_menu/Lassi/80. NAMKEEN LASSI.jpg',
  },
  {
    id: 'pudina-lassi',
    name: 'PUDINA LASSI',
    description: 'Menta, yogurt',
    price: 3.00,
    categoryId: 'lassi',
    image: '/new menu/Drink 7_menu/Lassi/81. PUDINA LASSI.jpg',
  },
];

// Categories list
export const categories = [
  { id: 'starter', name: 'Antipasti' },
  { id: 'fried', name: 'Fritti' },
  { id: 'grill', name: 'Griglia' },
  { id: 'chicken', name: 'Pollo' },
  { id: 'special_chicken_karahi', name: 'Specialità Pollo' },
  { id: 'lamb_karahi', name: 'Agnello' },
  { id: 'special_lamb_karahi', name: 'Specialità Agnello' },
  { id: 'vegetable', name: 'Vegetariano' },
  { id: 'insalata', name: 'Insalate' },
  { id: 'pane', name: 'Pane' },
  { id: 'riso', name: 'Riso' },
  { id: 'cafeteria', name: 'Caffetteria' },
  { id: 'soft_drinks', name: 'Bevande' },
  { id: 'lassi', name: 'Lassi' },
];

// Helper function to get items by category
export function getItemsByCategory(categoryId) {
  return menuItems.filter(item => item.categoryId === categoryId);
}

// Helper to get top seller items
export function getTopSellers() {
  return menuItems.filter(item => item.isTopSeller);
}

// Helper to find item by ID
export function getMenuItemById(id) {
  return menuItems.find(item => item.id === id);
}

export default menuItems;
